# -*- coding: utf-8 -*-
"""factorial

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-kFcEAVDLojzIwU7DUJBM5iD2uHJ8ulU
"""

n=5
fact=1
for i in range(1,n+1):
    fact = fact * i
print(fact)