# -*- coding: utf-8 -*-
"""fibonaccr

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1f0IsO-KPzC-HpyiYuQoKupipxHHI0qpo
"""

n=10
a=0
b=1
for i in range(n):
  print(a,end=" ")
  next=a+b
  a=b
  b=next